name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

# Set environment variables for consistent builds
env:
  NODE_ENV: production
  NEXT_TELEMETRY_DISABLED: 1

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Restore Next.js cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: |
          npm ci --prefer-offline --no-audit
          echo "Verifying TypeScript dependencies..."
          npm ls typescript @types/react @types/node || echo "Some TypeScript packages may not be installed"

      - name: Ensure TypeScript dependencies
        run: |
          npm install --save-dev typescript@^5 @types/react@^19 @types/node@^20 @types/react-dom@^19

      - name: Verify installation
        run: |
          npm ls typescript @types/react @types/node @types/react-dom
          echo "TypeScript setup verified"

      - name: Type check
        run: npm run type-check

      - name: Lint code
        run: npm run lint

      - name: Build Next.js application
        run: |
          npm run build
          echo "Build completed successfully"

      - name: Verify build output
        run: |
          ls -la out/
          echo "Build output verified"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
          name: github-pages
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages

      - name: Verify deployment
        run: |
          echo "Deployment completed successfully"
          echo "Site URL: ${{ steps.deployment.outputs.page_url }}"
